const $=(s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={name:'',story:0,teach:0,completed:[false,false,false],case:0,sort:0,response:0,history:[],opened:new Set(),speech:false};
const app=$('#app');

const story=[
 {title:'YOU TAUGHT ME TO LISTEN.',img:'assets/glorb.png',text:'Last mission, I learned to listen and wait for a pause.\n\nBut I have found a new Earth problem. I can hear the words and still get the feeling wrong.'},
 {title:'I KEEP GUESSING TOO FAST.',img:'assets/desk-tired.png',text:'I saw a student with their head on the desk. I thought something terrible had happened.\n\nThey were tired.\n\nOne clue was not enough.'},
 {title:'I ALSO TRY TO FIX EVERYTHING.',img:'assets/listen-friend.png',text:'A friend said their dog had died. I offered to find a replacement dog.\n\nThis did not help.\n\nSometimes people need us to listen, not fix.'},
 {title:'I NEED AN EARTH HELPER.',img:'assets/glorb.png',text:'{{name}}, can you help me learn empathy?\n\nTeach me how to notice clues, make a careful guess, check what someone needs and respond kindly.'}
];
const teach=[
 {title:'NOTICE',img:'assets/feelings-overview.png',meaning:'Look for more than one clue.',remember:'Notice the person’s face, body, words and situation.',note:'One clue can mean different things.'},
 {title:'GUESS',img:'assets/student-desk.png',meaning:'Make a careful guess.',remember:'Use words like “might”. A feeling guess is not a fact.',note:'Glorb update: clues are useful, but they are not proof.'},
 {title:'CHECK',img:'assets/listen-friend.png',meaning:'Find out what the person needs.',remember:'They might want help, listening, company or space. If you do not know, ask.',note:'I am deleting “fix every feeling” from my operating system.'},
 {title:'RESPOND',img:'assets/two-students.png',meaning:'Choose a kind response that fits.',remember:'Offer support without taking over. Respect their answer.',note:'“No thanks” is useful Earth data. I do not need to ask 14 more times.'}
];
const cases=[
 {title:'THE DESK',img:'assets/desk-tired.png',situation:'After lunch, a classmate has their head on the desk.',clues:{FACE:'Eyes closed. Face relaxed.',BODY:'Very still.',WORDS:'Not speaking.',SITUATION:'Just after lunch.'},options:['Furious','Tired','Proud','Excited'],correct:'Tired',success:'Tired fits the clues best. You would still check gently rather than assume.'},
 {title:'THE CLASS QUESTION',img:'assets/student-desk.png',situation:'A student answers incorrectly in front of the class and looks down.',clues:{FACE:'Face is red.',BODY:'Shoulders pulled in.',WORDS:'“Can we move on?”',SITUATION:'The mistake was public.'},options:['Happy','Content','Embarrassed','Tired'],correct:'Embarrassed',success:'Embarrassed fits several clues here.'},
 {title:'THE PRESENTATION',img:'assets/nervous-door.png',situation:'A student is waiting to give a presentation in five minutes.',clues:{FACE:'Eyes down.',BODY:'Fidgeting. Fast breaths.',WORDS:'“I’m worried I’ll mess it up.”',SITUATION:'A presentation is next.'},options:['Bored','Proud','Calm','Nervous'],correct:'Nervous',success:'Nervous fits the words, body clues and situation.'}
];
const sorts=[
 {id:'books',img:'assets/dropped-books.png',text:'A classmate drops their books and papers everywhere.',answer:'help',why:'There is a clear practical problem. Offer help.'},
 {id:'dog',img:'assets/listen-friend.png',text:'A friend tells you their dog died last night.',answer:'listen',why:'A loss cannot be fixed. Listening or staying with them may help.'},
 {id:'lunch',img:'assets/alone-lunch.png',text:'A classmate is sitting alone at lunch. You do not know if they want company.',answer:'check',why:'You do not know what they want. Check first.'},
 {id:'mistake',img:'assets/student-desk.png',text:'Someone looks upset after a mistake. You are not sure if they want to talk.',answer:'check',why:'You are not sure what would help. Ask gently.'}
];
const responses=[
 {title:'DROPPED BOOKS',img:'assets/dropped-books.png',text:'Papers are all over the floor and the student is in a hurry.',need:'CLEAR PRACTICAL PROBLEM → OFFER HELP',choices:[['“This is what happens when you carry too much.”',false,'That judges the mistake instead of helping.'],['“Do you want a hand picking those up?”',true,'Yes. It offers practical help and leaves room for them to say no.'],['Stand and watch.',false,'You can offer help first.']]},
 {title:'A FRIEND’S DOG DIED',img:'assets/listen-friend.png',text:'Your friend is speaking quietly and looks sad.',need:'LOSS / DIFFICULT FEELING → LISTEN OR STAY',choices:[['“I can find you another dog.”',false,'That tries to replace the loss instead of listening.'],['“At least you had a dog.”',false,'That can make the loss feel smaller than it is.'],['“I’m sorry. Do you want me to stay with you?”',true,'Yes. It shows care and offers company without taking over.']]},
 {title:'BEFORE A PRESENTATION',img:'assets/nervous-door.png',text:'A student is fidgeting and says they are worried about presenting.',need:'NERVOUS FEELING → LISTEN OR OFFER SUPPORT',choices:[['“Stop worrying.”',false,'Telling someone to stop a feeling does not help them with it.'],['“That sounds stressful. Want me to stay for a minute?”',true,'Yes. It notices the feeling and offers support.'],['“Most presentations are fine, so your worry makes no sense.”',false,'Facts do not cancel a feeling.']]},
 {title:'ALONE AT LUNCH',img:'assets/alone-lunch.png',text:'A classmate is sitting alone and looking down.',need:'NOT SURE WHAT THEY WANT → CHECK FIRST',choices:[['Sit down and start asking lots of questions.',false,'They may want space. Check first.'],['Walk past because they did not ask.',false,'You can check gently without taking over.'],['“Do you want some company?”',true,'Exactly. You are asking what they want.']]}
];

function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function person(s){return String(s).replaceAll('{{name}}',state.name||'Earth Expert')}
function setStage(t){$('#stageLabel').textContent=t}
function stopSpeech(){if('speechSynthesis' in window) speechSynthesis.cancel();state.speech=false;$('#readBtn').classList.remove('speaking');$('#readBtn').setAttribute('aria-pressed','false');$('#readLabel').textContent='READ'}
function pushHistory(view){if(state.history.at(-1)!==view) state.history.push(view); $('#backBtn').classList.toggle('hidden',state.history.length<2)}
function render(view,{push=true}={}){stopSpeech(); if(push)pushHistory(view); else $('#backBtn').classList.toggle('hidden',state.history.length<2); window.scrollTo(0,0); views[view](); requestAnimationFrame(()=>{const h=$('h1,h2',app);if(h){h.tabIndex=-1;h.focus({preventScroll:true})}})}

const views={
 boot(){setStage('START');app.innerHTML=`<section class="screen"><div class="shell split"><div class="visual-panel"><img src="assets/glorb.png" alt="Glorb"></div><article class="paper-panel"><div class="boot-copy"><p class="eyebrow">INCOMING TRANSMISSION</p><h1>GLORB & THE<br>EMPATHY MISSION</h1><p class="lead"><b>Glorb needs your help.</b> He can listen, but he still guesses feelings too quickly and tries to fix everything.</p><div class="boot-rule" aria-label="Empathy mission steps"><div><b>NOTICE</b></div><div><b>GUESS</b></div><div><b>CHECK</b></div><div><b>RESPOND</b></div></div><label class="eyebrow" for="playerName">EARTH HELPER // YOUR NAME</label><div class="name-row"><input id="playerName" maxlength="24" autocomplete="name" placeholder="Your name" value="${esc(state.name)}"><button id="start" class="button primary" ${state.name?'':'disabled'}>BEGIN</button></div><p class="fine">Your name is only used during this browser session and on your mission certificate.</p></div></article></div></section>`;const input=$('#playerName');const btn=$('#start');input.addEventListener('input',()=>{state.name=input.value.replace(/[^\p{L}\p{M}'’ .-]/gu,'').replace(/\s+/g,' ').trim().slice(0,24);btn.disabled=!state.name});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!btn.disabled)btn.click()});btn.addEventListener('click',()=>{try{sessionStorage.setItem('glorbEmpathyName',state.name)}catch{}state.story=0;render('story')})},
 story(){setStage('STORY');const s=story[state.story];app.innerHTML=`<section class="screen"><div class="shell split"><div class="visual-panel"><img src="${s.img}" alt="Story illustration"></div><article class="paper-panel"><p class="eyebrow">GLORB // FIELD MESSAGE</p><h2>${s.title}</h2><div class="story-copy">${person(s.text)}</div><div class="story-nav"><span class="count">${state.story+1} / ${story.length}</span><button id="next" class="button ink">${state.story===story.length-1?'MISSION BRIEFING':'CONTINUE'}</button></div></article></div></section>`;$('#next').onclick=()=>{if(state.story<story.length-1){state.story++;render('story')}else render('briefing')}},
 briefing(){setStage('BRIEFING');app.innerHTML=`<section class="screen"><div class="shell split"><div class="visual-panel"><img src="assets/two-students.png" alt="Two students talking"></div><article class="paper-panel compact"><p class="eyebrow">YOUR JOB</p><h2>HELP GLORB READ THE SITUATION.</h2><p class="lead">Empathy does not mean knowing exactly how someone feels. It means noticing, checking and responding with care.</p><div class="briefing-list"><div><span>1</span><p><b>NOTICE</b><small>Look at face, body, words and situation.</small></p></div><div><span>2</span><p><b>GUESS</b><small>Use “might”. Your first guess can be wrong.</small></p></div><div><span>3</span><p><b>CHECK</b><small>Find out what the person wants or needs.</small></p></div><div><span>4</span><p><b>RESPOND</b><small>Offer kind words or help, then respect their answer.</small></p></div></div><div class="intention"><b>WE ARE LEARNING TO:</b> notice clues about how someone might be feeling and choose a kind, helpful response.</div><button id="learn" class="button ink">LEARN THE RULE</button></article></div></section>`;$('#learn').onclick=()=>{state.teach=0;render('learn')}},
 learn(){setStage('LEARN');const c=teach[state.teach];app.innerHTML=`<section class="screen"><div class="shell learn-shell"><header class="mini-head"><div><p class="eyebrow light">EMPATHY RULE</p><h2>LEARN ONE STEP AT A TIME</h2></div><span class="step-count">STEP ${state.teach+1} / 4</span></header><div class="learn-card"><div class="learn-visual"><img src="${c.img}" alt="Illustration for ${c.title.toLowerCase()}"></div><article class="learn-copy"><span class="learn-number">STEP ${state.teach+1}</span><h2>${c.title}</h2><p class="lead"><b>${c.meaning}</b></p><div class="remember">${c.remember}</div><p class="glorb-note">GLORB // ${c.note}</p></article></div><footer class="learn-footer"><div class="tracker">${teach.map((_,i)=>`<span class="${i<=state.teach?'on':''}"></span>`).join('')}</div><div><button id="prev" class="button ghost" ${state.teach===0?'disabled':''}>BACK</button> <button id="next" class="button primary">${state.teach===3?'START MISSIONS':'NEXT'}</button></div></footer></div></section>`;$('#prev').onclick=()=>{if(state.teach>0){state.teach--;render('learn')}};$('#next').onclick=()=>{if(state.teach<3){state.teach++;render('learn')}else render('hub')}},
 hub(){setStage('MISSIONS');const cards=[['01','NOTICE + GUESS','READ THE CLUES','Use more than one clue before making a feeling guess.','detective'],['02','CHECK','HELP, LISTEN OR CHECK?','Decide what Glorb should do first.','sort'],['03','RESPOND','WHAT SHOULD GLORB SAY?','Choose words that match what the person needs.','respond']];app.innerHTML=`<section class="screen"><div class="shell hub-shell"><header class="mini-head"><div><p class="eyebrow light">EARTH HELPER CONSOLE</p><h2>TEACH GLORB 3 EMPATHY TOOLS</h2></div><span class="step-count">${state.completed.filter(Boolean).length} / 3 DONE</span></header><div class="helper-strip"><img src="assets/glorb.png" alt="Glorb"><p><b>${esc(state.name||'Earth Helper')}, you are Glorb’s helper.</b> Complete the missions in order so he can practise the full empathy rule.</p></div><div class="mission-grid">${cards.map((c,i)=>{const locked=i>0&&!state.completed[i-1],done=state.completed[i];return `<button class="mission-card ${done?'complete':''}" data-view="${c[4]}" ${locked?'disabled':''}><span class="num">${c[0]} // ${c[1]}</span><div><strong>${c[2]}</strong><p>${c[3]}</p></div><em>${done?'COMPLETE':locked?'LOCKED':'OPEN'}</em></button>`}).join('')}</div></div></section>`;$$('.mission-card:not(:disabled)').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='detective'){state.case=0;state.opened=new Set()}if(v==='sort')state.sort=0;if(v==='respond')state.response=0;render(v)})},
 detective(){setStage('MISSION 1');const c=cases[state.case];app.innerHTML=`<section class="screen"><div class="shell activity-shell"><header class="activity-head"><div><p class="eyebrow light">MISSION 01 // NOTICE + GUESS</p><h2>READ THE CLUES</h2><p class="activity-sub">Open at least 2 clues. Then choose the feeling that fits best. Remember: it is still a guess.</p></div><span class="step-count">CASE ${state.case+1} / ${cases.length}</span></header><div class="case-board"><article class="case-card"><div class="case-image"><img src="${c.img}" alt="Case illustration"></div><div><h3>${c.title}</h3><p class="case-text">${c.situation}</p><div class="clue-grid">${Object.entries(c.clues).map(([k,v])=>`<button class="clue ${state.opened.has(k)?'':'closed'}" data-k="${k}"><b>${k}</b><small>${state.opened.has(k)?v:'TAP TO OPEN'}</small></button>`).join('')}</div></div></article><aside class="answer-card"><p class="eyebrow">YOUR CAREFUL GUESS</p><h3>What might this person be feeling?</h3><div class="choices">${c.options.map(o=>`<button class="choice" data-answer="${o}" ${state.opened.size<2?'disabled':''}>${o}</button>`).join('')}</div><div id="feedback" class="feedback">${state.opened.size<2?`Open ${2-state.opened.size} more clue${2-state.opened.size===1?'':'s'} first.`:'Choose the feeling that fits the clues best.'}</div><button id="caseNext" class="button primary hidden">${state.case===cases.length-1?'FINISH MISSION':'NEXT CASE'}</button></aside></div><footer class="activity-foot"><span class="small-status">${state.opened.size} / 4 CLUES OPEN</span><button id="toHub" class="button ghost">BACK TO MISSIONS</button></footer></div></section>`;$$('.clue').forEach(b=>b.onclick=()=>{state.opened.add(b.dataset.k);render('detective')});$$('.choice').forEach(b=>b.onclick=()=>{const good=b.dataset.answer===c.correct;if(good){b.classList.add('correct');$$('.choice').forEach(x=>x.disabled=true);$('#feedback').className='feedback good';$('#feedback').textContent=c.success;$('#caseNext').classList.remove('hidden')}else{b.classList.add('wrong');b.disabled=true;$('#feedback').className='feedback bad';$('#feedback').textContent='Not the best fit yet. Use the clues you opened and try another answer.'}});$('#caseNext').onclick=()=>{if(state.case<cases.length-1){state.case++;state.opened=new Set();render('detective')}else{state.completed[0]=true;render('hub')}};$('#toHub').onclick=()=>render('hub')},
 sort(){setStage('MISSION 2');const c=sorts[state.sort];app.innerHTML=`<section class="screen"><div class="shell activity-shell"><header class="activity-head"><div><p class="eyebrow light">MISSION 02 // CHECK</p><h2>HELP, LISTEN OR CHECK?</h2><p class="activity-sub">One situation at a time. Choose what Glorb should do first.</p></div><span class="step-count">${state.sort+1} / ${sorts.length}</span></header><div class="sort-layout"><div class="sort-visual"><img src="${c.img}" alt="Situation illustration"></div><article class="sort-card-main"><span class="sort-counter">SITUATION ${state.sort+1}</span><p class="sort-situation"><b>${c.text}</b></p><div class="sort-options"><button class="sort-option" data-a="help"><b>HELP</b><small>Clear practical action</small></button><button class="sort-option" data-a="listen"><b>LISTEN</b><small>Feeling or loss</small></button><button class="sort-option" data-a="check"><b>CHECK</b><small>Not sure what they want</small></button></div><div id="feedback" class="feedback">Choose the best first step.</div><button id="sortNext" class="button primary hidden">${state.sort===sorts.length-1?'FINISH MISSION':'NEXT SITUATION'}</button><div class="sort-progress">${sorts.map((_,i)=>`<div class="${i<state.sort?'done':i===state.sort?'active':''}">${i<state.sort?'✓':i+1}</div>`).join('')}</div></article></div><footer class="activity-foot"><span class="small-status">RULE: HELP if practical. LISTEN for feelings. CHECK if unsure.</span><button id="toHub" class="button ghost">BACK TO MISSIONS</button></footer></div></section>`;$$('.sort-option').forEach(b=>b.onclick=()=>{if(b.dataset.a===c.answer){b.classList.add('correct');$$('.sort-option').forEach(x=>x.disabled=true);$('#feedback').className='feedback good';$('#feedback').textContent=c.why;$('#sortNext').classList.remove('hidden')}else{b.classList.add('wrong');b.disabled=true;$('#feedback').className='feedback bad';$('#feedback').textContent='Try again. Ask: is there a clear action, a feeling to listen to, or do I need to check what they want?'}});$('#sortNext').onclick=()=>{if(state.sort<sorts.length-1){state.sort++;render('sort')}else{state.completed[1]=true;render('hub')}};$('#toHub').onclick=()=>render('hub')},
 respond(){setStage('MISSION 3');const c=responses[state.response];app.innerHTML=`<section class="screen"><div class="shell activity-shell"><header class="activity-head"><div><p class="eyebrow light">MISSION 03 // RESPOND</p><h2>WHAT SHOULD GLORB SAY?</h2><p class="activity-sub">Use the person’s need as your clue. Wrong answers turn grey, so you can try again.</p></div><span class="step-count">${state.response+1} / ${responses.length}</span></header><div class="response-layout"><div class="response-visual"><img src="${c.img}" alt="Scenario illustration"></div><article class="response-card"><p class="eyebrow">${c.title}</p><p class="case-text">${c.text}</p><div class="need-box"><span>WHAT MIGHT HELP?</span><strong>${c.need}</strong></div><h3>Choose Glorb’s response.</h3><div class="choices">${c.choices.map((x,i)=>`<button class="choice" data-i="${i}">${x[0]}</button>`).join('')}</div><div id="feedback" class="feedback">Choose the response that best matches the need.</div><button id="responseNext" class="button primary hidden">${state.response===responses.length-1?'COMPLETE MISSION':'NEXT'}</button></article></div><footer class="activity-foot"><span class="small-status">KIND + USEFUL + DOES NOT TAKE OVER</span><button id="toHub" class="button ghost">BACK TO MISSIONS</button></footer></div></section>`;$$('.choice').forEach(b=>b.onclick=()=>{const [,good,msg]=c.choices[+b.dataset.i];if(good){b.classList.add('correct');$$('.choice').forEach(x=>x.disabled=true);$('#feedback').className='feedback good';$('#feedback').textContent=msg;$('#responseNext').classList.remove('hidden')}else{b.classList.add('wrong');b.disabled=true;$('#feedback').className='feedback bad';$('#feedback').textContent=msg+' Try another response.'}});$('#responseNext').onclick=()=>{if(state.response<responses.length-1){state.response++;render('respond')}else{state.completed[2]=true;render('complete')}};$('#toHub').onclick=()=>render('hub')},
 complete(){setStage('COMPLETE');app.innerHTML=`<section class="screen"><div class="shell split complete-shell"><div class="visual-panel"><img src="assets/glorb.png" alt="Glorb"></div><article class="paper-panel complete-panel"><p class="eyebrow">FINAL FIELD REPORT</p><h2>${esc(state.name||'Earth Helper')}, YOU HELPED GLORB.</h2><p class="lead">Glorb can now slow down, use more than one clue, check what a person wants and choose a response that fits.</p><div class="final-rule"><div><b>NOTICE</b><small>more than one clue</small></div><div><b>GUESS</b><small>use “might”</small></div><div><b>CHECK</b><small>what they need</small></div><div><b>RESPOND</b><small>kindly and respectfully</small></div></div><p class="glorb-quote">“Earth remains confusing. But I am now causing significantly less emotional chaos. Thank you, ${esc(state.name||'Earth Helper')}.” // GLORB</p><div class="certificate-cta"><div><b>EARTH HELPER CERTIFICATE</b><p>A record of the tools you helped Glorb practise.</p></div><button id="cert" class="button primary">VIEW CERTIFICATE</button></div><button id="replay" class="button ghost" style="margin-top:8px">REPLAY</button></article></div></section>`;$('#cert').onclick=()=>render('certificate');$('#replay').onclick=()=>location.reload()},
 certificate(){setStage('CERTIFICATE');const d=new Date().toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'});app.innerHTML=`<section class="screen certificate-screen"><div class="certificate-wrap"><div id="certificate" class="certificate" role="document" aria-label="Earth Helper certificate"><div class="certificate-art"><img src="assets/glorb.png" alt="Glorb"></div><div class="certificate-copy"><p class="certificate-kicker">CERTIFICATE OF EARTH ASSISTANCE</p><h1>GLORB EMPATHY MISSION</h1><p style="margin:0;font-size:.75rem">Awarded to</p><div class="certificate-name">${esc(state.name||'Earth Helper')}</div><p class="certificate-summary">for helping Glorb practise four empathy tools and make more careful, respectful choices with people on Earth.</p><div class="certificate-tools"><div><b>NOTICE</b><small>more than one clue</small></div><div><b>GUESS</b><small>carefully with “might”</small></div><div><b>CHECK</b><small>what the person wants</small></div><div><b>RESPOND</b><small>with care, then respect the answer</small></div></div><div class="certificate-footer"><span>${d}</span><span>GLORB SOCIAL SKILLS FRAMEWORK</span></div></div><div class="certificate-actions"><button id="certBack" class="button ink">BACK</button><button id="print" class="button primary">PRINT / SAVE PDF</button></div></div></div></section>`;$('#certBack').onclick=()=>render('complete');$('#print').onclick=()=>window.print()}
};

$('#backBtn').addEventListener('click',()=>{stopSpeech();if(state.history.length>1){state.history.pop();const prev=state.history.at(-1);render(prev,{push:false})}});
$('#teacherBtn').onclick=()=>{stopSpeech();$('#teacherModal').classList.remove('hidden');$('#closeTeacherBtn').focus()};
function closeTeacher(){$('#teacherModal').classList.add('hidden');$('#teacherBtn').focus()}
$('#closeTeacherBtn').onclick=closeTeacher;$('#closeTeacherBottom').onclick=closeTeacher;$('#teacherModal').addEventListener('click',e=>{if(e.target===$('#teacherModal'))closeTeacher()});
$('#readBtn').onclick=()=>{if(!('speechSynthesis' in window)){alert('Read aloud is not supported in this browser.');return}if(state.speech||speechSynthesis.speaking){stopSpeech();return}const active=$('.screen',app);if(!active)return;const clone=active.cloneNode(true);$$('button,.hidden,img',clone).forEach(n=>n.remove());const text=clone.textContent.replace(/\s+/g,' ').replace(/→/g,' then ').trim();const u=new SpeechSynthesisUtterance(text);u.rate=.92;u.lang='en-AU';u.onend=stopSpeech;u.onerror=stopSpeech;state.speech=true;$('#readBtn').classList.add('speaking');$('#readBtn').setAttribute('aria-pressed','true');$('#readLabel').textContent='STOP';speechSynthesis.speak(u)};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#teacherModal').classList.contains('hidden'))closeTeacher();else stopSpeech()}});
try{state.name=(sessionStorage.getItem('glorbEmpathyName')||'').slice(0,24)}catch{}
render('boot');
